name: test
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04,   target: linux,   platform: linux-x64 }
          - { os: macos-14,       target: darwin,  platform: darwin-arm64 }
          - { os: windows-latest, target: windows, platform: win32-x64 }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build for Windows
        if: ${{ matrix.target == 'windows' }}
        run: .\make.bat
      - name: Install ninja
        if: ${{ matrix.target == 'linux' || matrix.target == 'darwin' }}
        run: |
          apk update
          apk add git ninja bash build-base nodejs linux-headers
      - name: Build for Non-Windows
        if: ${{ matrix.target == 'linux' || matrix.target == 'darwin' }}
        run: ./make.sh
